apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-service # Recommended to add '-service' for clarity
  namespace: {{.Values.namespace}} # Harness will inject the namespace here
  labels:
    app: tic-tac-toe
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: tic-tac-toe # DO NOT CHANGE THIS. This is the stable anchor point.
