pipeline:
  name: shamini-tictactoe-CD
  identifier: shaminitictactoeCD
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: blue-green-deployment
        identifier: deploygreenv2
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          environment:
            environmentRef: Shamini_tictactoe_test_env
            deployToAll: false
            infrastructureDefinitions:
              - identifier: shamini_tictactoe_infra
          execution:
            steps:
              - step:
                  name: Stage Deployment
                  identifier: stageDeployment
                  type: K8sBlueGreenDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  name: Swap primary with stage service
                  identifier: bgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
                  when:
                    stageStatus: Success
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
          service:
            serviceRef: shamini_tic_tac_toe_app
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: SKIP_NEXT_STEP
            type: String
            description: ""
            required: true
            value: <+input>.executionInput().selectOneFrom(true,false)
  allowStageExecutions: true
